name: thingtranslator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: ^0.6.7+2
  path_provider: ^1.6.11
  path: ^1.6.4
  flutter_svg: ^0.17.4
  flutter_text_to_speech: ^3.0.7
  provider: ^4.0.0
  sqflite: ^1.3.0
  easy_localization: ^2.3.2
  camera:
    git:
      url: git://github.com/hillelcoren/plugins.git
      path: packages/camera

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translation/

  fonts:
    - family: OperatorMono
      fonts:
        - asset: assets/font/OperatorMono.ttf
          weight: 200
